[Service]
# Assign the wpa_supplicant process to the 'wifi' group.
# This allows processes in the 'wifi' group to access control sockets and
# other files created by wpa_supplicant, depending on permissions.
Group=wifi

# Set the default umask to 007.
UMask=007

# Override ExecStart:
ExecStart=
ExecStart=/usr/sbin/wpa_supplicant -u -O /run/wpa_supplicant
