#!/bin/sh
########################################################################
#Copyright (c) 2017, The Linux Foundation. All rights reserved.
#
#Redistribution and use in source and binary forms, with or without
#modification, are permitted provided that the following conditions are
#met:
#    * Redistributions of source code must retain the above copyright
#      notice, this list of conditions and the following disclaimer.
#    * Redistributions in binary form must reproduce the above
#      copyright notice, this list of conditions and the following
#      disclaimer in the documentation and/or other materials provided
#      with the distribution.
#    * Neither the name of The Linux Foundation nor the names of its
#      contributors may be used to endorse or promote products derived
#      from this software without specific prior written permission.
#
#THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED
#WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT
#ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
#BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
#BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
#OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
#IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#########################################################################

###################################################################################
#Changes from Qualcomm Innovation Center are provided under the following license:
#
#Copyright (c) 2024 Qualcomm Innovation Center, Inc. All rights reserved.
#
#Redistribution and use in source and binary forms, with or without
#modification, are permitted (subject to the limitations in the
#disclaimer below) provided that the following conditions are met:
#
#    * Redistributions of source code must retain the above copyright
#      notice, this list of conditions and the following disclaimer.
#
#    * Redistributions in binary form must reproduce the above
#      copyright notice, this list of conditions and the following
#      disclaimer in the documentation and/or other materials provided
#      with the distribution.
#
#    * Neither the name of Qualcomm Innovation Center, Inc. nor the names of its
#      contributors may be used to endorse or promote products derived
#      from this software without specific prior written permission.
#
#NO EXPRESS OR IMPLIED LICENSES TO ANY PARTY'S PATENT RIGHTS ARE
#GRANTED BY THIS LICENSE. THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT
#HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED
#WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
#IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
#ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
#DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
#GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER
#IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
#IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
###################################################################################

### BEGIN INIT INFO
# Provides: weston
# Required-Start: $local_fs $remote_fs
# Required-Stop: $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO

if test -e /etc/default/weston ; then
        . /etc/default/weston
fi

killproc() {
        pid=`/bin/pidof $1`
        [ "$pid" != "" ] && kill $pid
}

launch_weston=`getprop persist.display.launch.weston.at.bootup`

read CMDLINE < /proc/cmdline
for x in $CMDLINE; do
        case $x in
        weston=false)
        echo "Weston disabled"
        exit 0;
                ;;
        esac
done

case "$1" in
  start)
        . /etc/profile

        # This is all a nasty hack
        if test -z "$XDG_RUNTIME_DIR"; then
            export XDG_RUNTIME_DIR=/dev/socket/weston
        fi

        if test -z "$XDG_PICTURES_DIR"; then
            export XDG_PICTURES_DIR=/data/misc/display
        fi

        if [[ -z "$SHELL" && -x "/bin/sh" ]]; then
            export SHELL=/bin/sh
        fi

        if [ -f /sys/devices/soc0/soc_id ]; then
            soc_id=`cat /sys/devices/soc0/soc_id`
            if [ "$soc_id" == 497 ] || [ "$soc_id" == 498 ]; then
                `setprop sdm.max_pipe_config 2`
            fi
        fi

        export PATH_DRM_NODE=/dev/dri
        filename_drm=$(find $PATH_DRM_NODE  -name 'card0' -print -quit )
        while  [ -z "$filename_drm" ]; do
            sleep 1
            filename_drm=$(find $PATH_DRM_NODE  -name 'card0' -print -quit )
        done

        # Settle udev before by-path detection to avoid race with symlink creation
        udevadm settle --timeout=10

        echo "WESTON INITIALIZATION STARTUP"

        # Detect KMS-capable DRM cards via stable by-path symlinks (probe-order independent)
        weston_opts="--idle-time=0 --continue-without-input"
        additional_cards=""
        first_kms_card=""
        kms_cards=""

        for path_link in /dev/dri/by-path/platform-*-card; do
            [ -L "$path_link" ] || continue
            card=$(readlink -f "$path_link")
            [ -n "$card" ] || continue
            card_name=$(basename "$card")
            [ -n "$card_name" ] || continue

            has_kms=0
            for connector in /sys/class/drm/${card_name}-*; do
                [ -d "$connector" ] && has_kms=1 && break
            done

            if [ "$has_kms" -eq 1 ]; then
                platform_addr=$(echo "$path_link" | sed 's/.*platform-\([0-9a-f]*\).*/\1/')
                [ -n "$platform_addr" ] && kms_cards="$kms_cards $platform_addr:$card_name"
            fi
        done

        sorted_cards=$(echo "$kms_cards" | tr ' ' '\n' | grep -v '^$' | sort | cut -d: -f2)

        for card_name in $sorted_cards; do
            if [ -z "$first_kms_card" ]; then
                first_kms_card="$card_name"
            else
                additional_cards="${additional_cards:+$additional_cards,}$card_name"
            fi
        done

        if [ -n "$additional_cards" ]; then
            echo "Multi-DPU detected, launching Weston with additional devices: $additional_cards"
            weston_opts="$weston_opts --additional-devices=$additional_cards"
        fi

        weston $weston_opts &

        # Wait for wayland socket node to be created with a maximum of 100 attempts.
        attempts=0
        max_attempts=100

        filename=$(find $XDG_RUNTIME_DIR -maxdepth 1 -name 'wayland-*' -print -quit)
        while [ -z "$filename" ] && [ $attempts -lt $max_attempts ]; do
            sleep 0.1
            attempts=$((attempts + 1))
            filename=$(find $XDG_RUNTIME_DIR -maxdepth 1 -name 'wayland-*' -print -quit)
        done

        if [ -z "$filename" ]; then
            echo "Failed to find wayland socket after $max_attempts attempts."
        else
            echo "Found wayland socket: $filename"
            chown -hR system:video $XDG_RUNTIME_DIR
            chmod 776 /dev/socket/weston/wayland-1
        fi
  ;;

  stop)
        echo "Stopping Weston"
  ;;

  restart)
    $0 stop
        sleep 1
        $0 start
  ;;

  *)
        echo "usage: $0 { start | stop | restart }"
  ;;
esac

exit 0
