# configuration file for Weston
[core]
require-outputs=none

[launcher]
icon=/usr/share/weston/terminal.png
path=/usr/bin/weston-terminal

[output]
name=LVDS-1
mode=off

[launcher]
icon=/etc/media/Qdemo.png
path=/usr/bin/Qdemo
