name: Build Yocto

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  compile:
    env:
      CACHE_DIR: /srv/gh-runners/quic-yocto
      DL_DIR: ${{ env.CACHE_DIR }}/downloads
      SSTATE_DIR: ${{ env.CACHE_DIR }}/sstate-cache
      KAS_WORK_DIR: ${{ env.GITHUB_WORKSPACE }}/../kas
    strategy:
      max-parallel: 1
      fail-fast: true
      matrix:
        machine:
          - qcm6490-idp
          - qcs6490-rb3gen2-core-kit
          - sa8775p-ride-sx
    runs-on: [self-hosted, x86]
    name: ${{ matrix.machine }}/poky/systemd
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cleanup sstate-cache
        run: |
          SSTATE_CACHE_MANAGEMENT="${PWD}/poky/scripts/sstate-cache-management.py --cache-dir  ${{ env.SSTATE_DIR }} --remove-duplicated --remove-orphans --debug"
          #FIXME: only to check, when done remove the "echo no" and add the "--yes" arg
          SSTATE_CACHE_MANAGEMENT="echo no | $SSTATE_CACHE_MANAGEMENT"
          kas shell ci/${{ matrix.machine }}.yml --command "$SSTATE_CACHE_MANAGEMENT"
