name: Build Yocto

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  yocto-check-layer:
    runs-on: [self-hosted, x86]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run yocto-check-layer
        run: |
          ci/yocto-check-layer.sh

  compile:
    strategy:
      fail-fast: true
      matrix:
        machine:
          - qcm6490-idp
          - qcs6490-rb3gen2-core-kit
          - sa8775p-ride-sx
    runs-on: [self-hosted, x86]
    name: ${{ matrix.machine }}/poky/systemd
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Kas build
        run: |
          export DL_DIR=/srv/gh-runners/quic-yocto/downloads
          export SSTATE_DIR=/srv/gh-runners/quic-yocto/sstate-cache
          mkdir -p $DL_DIR
          mkdir -p $SSTATE_DIR
          mkdir build
          cd build
          kas build ../ci/${{ matrix.machine }}.yml
